/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sampledb;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sampledb.MySql;

/**
 *
 * @author Johan Gil
 */
public class Inicio extends javax.swing.JFrame {

    DefaultTableModel model;
    Connection conn;
    Statement sent;
    funciones herramientas = new funciones();

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);//abrir aplicacion en el centro de la pantalla
        conn = MySql.getConnection();
        Desactivar();//Desactiva las casillas de ingreso de datos
        Llenar(); //llenar el jtable usuarios con los datos de mysql
        cerrar();//Confirmar salida de la aplicacion
        bttGuardarUsuarioNuevo.setVisible(false);
        bttGuardarmodif.setVisible(false);
        
    }

    void Desactivar() {
        txtId.setEditable(false);
        txtUsuario.setEditable(false);
        txtContraseña.setEditable(false);
        txtNombreCompleto.setEditable(false);
        txtCorreoElectronico.setEditable(false);
    }

    void Limpiar() {
        txtId.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtNombreCompleto.setText("");
        txtCorreoElectronico.setText("");
    }

    void Habilitar() {
        txtId.setEditable(true);
        txtUsuario.setEditable(true);
        txtContraseña.setEditable(true);
        txtNombreCompleto.setEditable(true);
        txtCorreoElectronico.setEditable(true);
    }

    void HabilitarModificacion() {
        txtContraseña.setEditable(true);
        txtNombreCompleto.setEditable(true);
        txtCorreoElectronico.setEditable(true);
    }
    
    
    //Metodo para confirmar el cierre del jframe
    void cerrar(){
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
                    confirmarSalida();
                }
            });
            this.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Conflicto en el metodo cerrar","ADVERTENCIA",JOptionPane.ERROR);
        }
    }
    
    //CONFIRMAR SALIDA
    void confirmarSalida(){
        int valor = JOptionPane.showConfirmDialog(this, "¿Esta seguro de cerrar la aplicacion?","Advertencia",JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Gracias por su visita, hasta pronto","GRACIAS",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }

    void Llenar() {
        try {
            conn = MySql.getConnection();
            String[] titulos = {"user_id", "username", " password", "fullname", "email"};
            String sql = "select * from users";
            model = new DefaultTableModel(null, titulos);
            sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);

            String[] fila = new String[5];
            while (rs.next()) {
                fila[0] = rs.getString("user_id");
                fila[1] = rs.getString("username");
                fila[2] = rs.getString("password");
                fila[3] = rs.getString("fullname");
                fila[4] = rs.getString("email");

                model.addRow(fila);
            }
            tabla_usuarios.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema en la funcion llenar tabla");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        txtNombreCompleto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bttGuardarUsuarioNuevo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        bttGuardarmodif = new javax.swing.JButton();
        btt_nuevo = new javax.swing.JButton();
        bttModificar = new javax.swing.JButton();
        btt_Eliminar = new javax.swing.JButton();
        bttActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_usuarios = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USUARIOS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Usuario"));
        jPanel1.setToolTipText("");

        jLabel3.setText("id");

        jLabel4.setText("usuario");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Nombre Completo");

        bttGuardarUsuarioNuevo.setText("Guardar usuario Nuevo");
        bttGuardarUsuarioNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGuardarUsuarioNuevoActionPerformed(evt);
            }
        });

        jLabel7.setText("Correo electronico");

        bttGuardarmodif.setText("Guardar modificacion");
        bttGuardarmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGuardarmodifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addComponent(txtId)
                    .addComponent(txtContraseña)
                    .addComponent(txtNombreCompleto)
                    .addComponent(txtCorreoElectronico))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(bttGuardarUsuarioNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(bttGuardarmodif)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttGuardarUsuarioNuevo)
                    .addComponent(bttGuardarmodif))
                .addContainerGap())
        );

        btt_nuevo.setText("Nuevo");
        btt_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_nuevoActionPerformed(evt);
            }
        });

        bttModificar.setText("Modificar");
        bttModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttModificarActionPerformed(evt);
            }
        });

        btt_Eliminar.setText("Eliminar");
        btt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_EliminarActionPerformed(evt);
            }
        });

        bttActualizar.setText("Actualizar");
        bttActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttActualizarActionPerformed(evt);
            }
        });

        tabla_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_usuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btt_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btt_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btt_nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btt_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttActualizar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttGuardarUsuarioNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGuardarUsuarioNuevoActionPerformed
        try {
            int id = Integer.parseInt(txtId.getText());
            String name = txtUsuario.getText();
            String pass = txtContraseña.getText();
            String full = txtNombreCompleto.getText();
            String correo = txtCorreoElectronico.getText();
            herramientas.insert(id, name, pass, full, correo);
            JOptionPane.showMessageDialog(null, "Se guardo el usuario " + name);
            Limpiar();
            Desactivar();
        } catch (Exception i) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos");
        }
    }//GEN-LAST:event_bttGuardarUsuarioNuevoActionPerformed

    private void btt_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_nuevoActionPerformed
        Limpiar();
        Habilitar();
        bttGuardarUsuarioNuevo.setVisible(true);
        bttGuardarmodif.setVisible(false);
    }//GEN-LAST:event_btt_nuevoActionPerformed

    private void bttActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttActualizarActionPerformed
        Llenar();
    }//GEN-LAST:event_bttActualizarActionPerformed

    private void bttGuardarmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGuardarmodifActionPerformed
        try {

            int id = Integer.parseInt(txtId.getText());
            String name = txtUsuario.getText();
            String pass = txtContraseña.getText();
            String full = txtNombreCompleto.getText();
            String correo = txtCorreoElectronico.getText();
            herramientas.update(pass, full, correo, id);
            JOptionPane.showMessageDialog(null, "Se actualizaron los datos del usuario " + name, "OPERACION COMPLETA", JOptionPane.INFORMATION_MESSAGE);
            Limpiar();
            Desactivar();
        } catch (Exception i) {
            JOptionPane.showMessageDialog(null, "Datos invalidos");
        }
    }//GEN-LAST:event_bttGuardarmodifActionPerformed

    private void bttModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttModificarActionPerformed

        int fsel = tabla_usuarios.getSelectedRow();
        try {
            String id, username, pass, fullname, email;
            if (fsel == -1) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar el usuario que desea modificar", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            } else {
                HabilitarModificacion();
                bttGuardarUsuarioNuevo.setVisible(false);
                bttGuardarmodif.setVisible(true);
                model = (DefaultTableModel) tabla_usuarios.getModel();
                id = tabla_usuarios.getValueAt(fsel, 0).toString();
                username = tabla_usuarios.getValueAt(fsel, 1).toString();
                pass = tabla_usuarios.getValueAt(fsel, 2).toString();
                fullname = tabla_usuarios.getValueAt(fsel, 3).toString();
                email = tabla_usuarios.getValueAt(fsel, 4).toString();
                txtId.setText(id);
                txtUsuario.setText(username);
                txtContraseña.setText(pass);
                txtNombreCompleto.setText(fullname);
                txtCorreoElectronico.setText(email);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema en la funcion modificar usuario");
        }
    }//GEN-LAST:event_bttModificarActionPerformed

    private void btt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_EliminarActionPerformed
        int fsel = tabla_usuarios.getSelectedRow();
        try {
            int id;
            if (fsel == -1) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar el usuario que desea eliminar", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            } else {
                model = (DefaultTableModel) tabla_usuarios.getModel();
                id = Integer.parseInt(tabla_usuarios.getValueAt(fsel, 0).toString());
                herramientas.delete(id);
                JOptionPane.showMessageDialog(null, "Se elimino el usuario", "OPERACION COMPLETA", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema en la funcion eliminar");
        }
    }//GEN-LAST:event_btt_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttActualizar;
    private javax.swing.JButton bttGuardarUsuarioNuevo;
    private javax.swing.JButton bttGuardarmodif;
    private javax.swing.JButton bttModificar;
    private javax.swing.JButton btt_Eliminar;
    private javax.swing.JButton btt_nuevo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabla_usuarios;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
